version: "3.7"
services: 
    database:
      image: "topaztechnology/mssql-server-linux:latest"
      privileged: false
      ports:
        - ${DB_PORT}:1433
      environment:
        SA_PASSWORD: ${DB_PASSWORD}
        ACCEPT_EULA: "Y"